services:
  jenkins:
    build: .
    ports:
      - 8080:8080
      - 50000:50000
        #environment:
      #  GA: "$${stat -c '%g' /var/run/docker.sock}"
    group_add: 
      - 999
    volumes:
      - "jenkins_home:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
volumes:
  jenkins_home:
