version: '3.8'

services:
  backend:
    build: .
    ports:
      - 8090:8080
    environment:
      - POSTGRES_DB=example
  jenkins:
    image: jenkins/jenkins
    ports: 
      - 8080:8080
    volumes:
      - jenkins_volume:/var/jenkins_home
volumes:
  jenkins_volume:
